services:
  - type: web
    name: kriyaman-api
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: SERPAPI_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: BACKEND_URL
        sync: false

  - type: web
    name: kriyaman-ui
    env: python
    rootDir: frontend
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run ui.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: API_URL
        fromService:
          name: kriyaman-api
          type: web
          property: host
